name: Métricas del perfil

on:
  schedule:
    - cron: "0 6 * * *"   # una vez al día
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: DannieDev
          filename: github-metrics.svg
          template: classic
          base: header, activity, community
          config_timezone: America/Mexico_City
          config_display: regular
          repositories_affiliations: owner, collaborator, organization_member
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
